typography_spectrum: 0.60351
color:
  brandColors:
    - '#ffffff'
    - '#357fbe'
    - '#ac9762'
    - '#151b4d'
    - '#63533d'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26636
analytics:
  google: null
  facebook: null
  twitter: null
name: Vicki Lea
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Vicki Lea - Biography, Experience and Creative Achievements'
description: 'Biography, Experience and Creative Achievements'
purpose: []
