name: Vicki Lea
favicon: null
layout_spectrum: 0.58202
typography_spectrum: 0.60351
title: 'Vicki Lea - Biography, Experiences and Creative Achievements'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010008'
    - '#701d0b'
    - '#5b8b97'
    - '#fffdff'
    - '#575022'
  brandStrength: 0.625
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
