name: Vicki Lea
favicon: null
layout_spectrum: 0.33975
typography_spectrum: 0.67072
title: 'Vicki Lea - Biography, Experiences and Creative Achievements'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d8eced'
    - '#818d8f'
    - '#ffba5f'
    - '#6eb4f0'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
