name: VickiLea
favicon: null
layout_spectrum: 0.8806976706255227
typography_spectrum: 0.76137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0058ff'
    - '#00d6ff'
    - '#00a2ff'
    - '#5d4444'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.7238519722595811
  rhythmicContrast: 0.75
purpose: []
