name: Vicki Lea
favicon: null
layout_spectrum: 0.84106
typography_spectrum: 0.60351
title: 'Vicki Lea - Biography, Experiences and Creative Achievements'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0054ff'
    - '#007487'
    - '#00daff'
    - '#653230'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
