name: Vicki Lea
favicon: null
layout_spectrum: 0.84106
typography_spectrum: 0.60351
title: 'Vicki Lea - Biography, Experience and Creative Achievements'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7595b0'
    - '#89755c'
    - '#61533a'
    - '#b7a080'
    - '#d3bfa6'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
